### ISSUE TITLE
Good project.

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [RemeaMiku/LXNaviPDR#1]
But I couldn't test it, I realized that there is a local NaviSharp library, I removed it and added the nuget package, but without success, there are a lot of things that are missing.

EulerAngle and others

I'm looking at the library and trying to get things working, if you can help I would appreciate it.

**Comment by RemeaMiku** [comment]
Oh, the project version of NaviSharp referenced by this repository is an old one. And a lot of things in the nuget package have been changed. For example, the EulerAngle you mentioned was changed to EulerAngles.

I've uploaded the old version of NaviSharp.dll under the LXNavi.Core\libraries directory. You can try referencing it directly.

**Comment by andersonvieiragomeslopes** [comment]
Thanks

![image](https://github.com/RemeaMiku/LXNaviPDR/assets/26186056/5e275280-fa3e-45fb-bad9-249dd9c5329a)

The project here worked, but I don't know if my adjustments are correct.

**Comment by andersonvieiragomeslopes** [comment]
![image](https://github.com/RemeaMiku/LXNaviPDR/assets/26186056/0bcc4cde-2eca-4765-980a-e4e3972697fa)

**Comment by andersonvieiragomeslopes** [comment]
![image](https://github.com/RemeaMiku/LXNaviPDR/assets/26186056/c1172b0d-4611-45ba-94ed-64287df70606)

**Comment by RemeaMiku** [comment]
Yes, they are all correct

**Comment by andersonvieiragomeslopes** [comment]
These are simple adjustments, but if you want a PR, let me know.
Thank you for your help.

**Comment by RemeaMiku** [comment]
Oh yes, your PR will help a lot. Thank you!

**Comment by andersonvieiragomeslopes** [comment]
> Oh yes, your PR will help a lot. Thank you!

I will fork your project and send the PR, thanks for all your help.
